name: Auto PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}  # 👈 Usando o PAT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB }}  # 👈 Usando o PAT aqui também
          title: "🔄 Auto: Develop → Main"
          body: |
            ## 🤖 PR Automático
            
            Alterações da branch `develop` prontas para produção.
            
            ### ✅ Checklist
            - [ ] Code review realizado
            - [ ] Testes passando
            - [ ] Migrations validadas (se aplicável)
          branch: auto-merge-develop-to-main
          base: main
          labels: automated-pr