name: Auto PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - name: Check if PR already exists
        id: check-pr
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          existing_pr=$(gh pr list --head develop --base main --state open --json number --jq '.[0].number')
          if [ -n "$existing_pr" ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$existing_pr" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-pr.outputs.pr_exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          gh pr create \
            --title "🔄 Auto: Develop → Main" \
            --body "## 🤖 PR Automático

          Alterações da branch \`develop\` prontas para produção.

          ### ✅ Checklist
          - [ ] Code review realizado
          - [ ] Testes passando
          - [ ] Migrations validadas (se aplicável)" \
            --head develop \
            --base main

      - name: Update existing PR
        if: steps.check-pr.outputs.pr_exists == 'true'
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          echo "PR #${{ steps.check-pr.outputs.pr_number }} já existe e foi atualizado automaticamente"